[project]
name = "copier-pulumi-project"
version = "0.1.0"
description = "Template for a Pulumi Project that is just creating infrastructure (no application code)"
readme = "README.md"
requires-python = ">=3.12.7"
dependencies = [
    # Managed by upstream template
    "pytest>=8.3.5",
    "pytest-cov>=6.1.1",
    "pytest-randomly>=3.16.0",
    "pyright[nodejs]>=1.1.400",
    "copier>=9.7.1",
    "copier-templates-extensions>=0.3.1"

    # Specific to this template


]
